"""Accesstoken table and UserModel table created

Revision ID: da14eba2bfe2
Revises: 4cbe50a303e5
Create Date: 2024-12-19 12:30:52.204896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da14eba2bfe2'
down_revision: Union[str, None] = '4cbe50a303e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usermodel_age', table_name='usermodel')
    op.drop_index('ix_usermodel_name', table_name='usermodel')
    op.drop_table('usermodel')
    op.drop_table('accesstoken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstoken',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('access_token', sa.VARCHAR(), nullable=False),
    sa.Column('token_type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usermodel',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index('ix_usermodel_name', 'usermodel', ['name'], unique=False)
    op.create_index('ix_usermodel_age', 'usermodel', ['age'], unique=False)
    # ### end Alembic commands ###
